$schema: https://azuremlschemas.azureedge.net/latest/amlCompute.schema.json 
name: cc-mt-mslearn
type: amlcompute
size: STANDARD_DS11_V2
min_instances: 1
max_instances: 2
idle_time_before_scale_down: 120
location: westeurope