name: Trigger a workflow on PR creation

on:
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Use Python version 3.8
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Install Flake8
      run: |
        pip install --upgrade pip
        python -m pip install flake8
    - name: Run linting tests
      run: | 
        flake8 src/model/
  unit_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Use Python version 3.8
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Install requirements
      run: |
        pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Run Python unit tests
      run: |
        pytest tests/
      