name: Deploy a registered model from Prod

on:
  push:
    branches:
      main


env:
  MODEL_NAME_DEV: diabetes-logreg-model-dev
  RUN_NAME_DEV: diabetes-experiment-dev
  MODEL_NAME_PROD: diabetes-logreg-model-prod
  RUN_NAME_PROD: diabetes-experiment-prod
  RESOURCE_GROUP_NAME: rg-mt-mslearn
  WORKSPACE_NAME: ws-mt-mslearn
  ENDPOINT_NAME: ep-mt-mslearn
  DEPLOYMENT_NAME: model-deployment-mt-mslearn


jobs:
  train-dev:
    environment: dev
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Azure Machine Learning job
      run: |
        az ml job create --name ${{ env.RUN_NAME_DEV }} --file src/job_dev.yml --resource-group ${{ env.RESOURCE_GROUP_NAME }} --workspace-name ${{ env.WORKSPACE_NAME }}
  train-prod:
    needs: train-dev
    environment: prod
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Azure Machine Learning job
      id: trigger_prod_job
      run: |
        az ml job create --name ${{ env.RUN_NAME_PROD }} --file src/job_prod.yml --resource-group ${{ env.RESOURCE_GROUP_NAME }} --workspace-name ${{ env.WORKSPACE_NAME }}
  deploy-prod:
    needs: train-prod
    environment: prod
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Register Prod model
      run: |
        az ml model create --name ${{ env.MODEL_NAME_PROD }} \
          --path azureml://jobs/${{ env.RUN_NAME_PROD }}/outputs/artifacts/paths/model/
    - name: Create Endpoint
      run: |
        az ml online-endpoint create ${{ env.ENDPOINT_NAME }} --file endpoint.yml --resource-group ${{ env.RESOURCE_GROUP_NAME }} --workspace-name ${{ env.WORKSPACE_NAME }}
    - name: Deploy Model
      run: |
        az ml model deploy --name ${{ env.DEPLOYMENT_NAME }} --model ${{ env.MODEL_NAME_PROD }} --resource-group ${{ env.RESOURCE_GROUP_NAME }} --workspace-name ${{ env.WORKSPACE_NAME }}