name: Deploy a registered model from Prod

on:
  push:
    branches:
      main


env:
  MODEL_NAME: diabetes-logreg-model
  RUN_NAME: diabetes-experiment


jobs:
  train-dev:
    environment: dev
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Azure Machine Learning job
      run: |
        az ml job create --name ${{ env.MODEL_NAME }}-dev --file src/job_dev.yml --set inputs.train_data.path= --resource-group rg-mt-mslearn --workspace-name ws-mt-mslearn
  train-prod:
    needs: train-dev
    environment: prod
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Azure Machine Learning job
      id: trigger_prod_job
      run: |
        az ml job create --name ${{ env.MODEL_NAME }}-prod --file src/job_prod.yml --resource-group rg-mt-mslearn --workspace-name ws-mt-mslearn
  deploy-prod:
    needs: train-prod
    environment: prod
    runs-on: ubuntu-latest
    steps:  
    - name: Register Prod model
      run: |
          az ml model create --name ${{ env.MODEL_NAME }}-prod \
          --path azureml://jobs/${{ env.RUN_NAME }}/outputs/artifacts/paths/model/