name: Manually trigger an Azure Machine Learning job

on:
  push:
    branches:
      main

jobs:
  train-dev:
    environment: dev
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Azure Machine Learning job
      run: |
        az ml job create --file src/job_dev.yml --resource-group rg-mt-mslearn --workspace-name ws-mt-mslearn
  train-prod:
    needs: train-dev
    environment: prod
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Azure Machine Learning job
      run: |
        az ml job create --file src/job_prod.yml --resource-group rg-mt-mslearn --workspace-name ws-mt-mslearn


